functions:
  test:
    handler: src/handlers/test.test
  airbnb_send_message:
    handler: src/handlers/airbnb/message/send.send
    events:
      - http:
          path: message
          method: post
          cors: true
  schedule_new_booking:
      handler: src/handlers/schedule/new-booking.newBooking
      timeout: 20
      events:
        - schedule:
            enabled: true
            rate: cron(0/${self:custom.config.aws.schedule.schedule_new_booking.interval} * * * ? *)
  schedule_before_checkout:
    handler: src/handlers/schedule/before-checkout.sendMessage
    events:
      - schedule:
          enabled: true
          rate: cron(0 12 * * ? *)
    timeout: 20
  google_api_call:
    handler: src/handlers/google/api.call
    timeout: 20
  schedule_before_checkin:
      handler: src/handlers/schedule/before-checkin.beforeCheckin
      events:
        - schedule:
            enabled: true
            rate: cron(0 1 * * ? *)
      timeout: 20

resources:
  Resources:
    Bookings:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Reservations