tables:
  AirbnbManagerThreadCounts: AirbnbManagerThreadCounts-dev
  AirbnbManagerResponses: AirbnbManagerResponses-dev
  AirbnbManagerTest: AirbnbManagerTest-dev

functions:
  test:
    handler: src/handlers/test.test
  schedule_new_booking:
    handler: src/handlers/schedule/new-booking.newBooking
    events:
      - schedule:
          enabled: false
          rate: cron(0/${self:custom.config.aws.schedule.schedule_new_booking.interval} * * * ? *)
  airbnb_send_message:
    handler: src/handlers/airbnb/message/send.send
    events:
      - http:
          path: message
          method: post
          cors: true
  schedule_before_checkout:
    handler: src/handlers/schedule/before-checkout.sendMessage
    timeout: 20
  schedule_save_new_bookings:
    handler: src/handlers/schedule/save.save
    timeout: 20
  schedule_before_checkin:
    handler: src/handlers/schedule/before-checkin.beforeCheckin
    timeout: 20
  google_api_call:
    handler: src/handlers/google/api.call

resources:
  Resources:
    Bookings:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Reservations-dev