functions:
  test:
    handler: src/handlers/test.test
  schedule_new_booking:
    handler: src/handlers/schedule/new-booking.newBooking
  airbnb_send_message:
    handler: src/handlers/airbnb/message/send.send
    events:
      - http:
          path: message
          method: post
          cors: true
  schedule_before_checkout:
    handler: src/handlers/schedule/before-checkout.sendMessage
    timeout: 20
  schedule_before_checkin:
    handler: src/handlers/schedule/before-checkin.beforeCheckin
    timeout: 20,
  schedule_after_checkin:
    handler: src/handlers/schedule/after-checkin.handler
    timeout: 20
  google_api_call:
    handler: src/handlers/google/api.call
    timeout: 20

resources:
  Resources:
    Bookings:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: Reservations-dev